name: "vercel alias"
on:
  repository_dispatch:
    types:
      - "vercel.deployment.success"
jobs:
  alias:
    name: "Alias vercel deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.15.0"
      - name: "Install vercel"
        run: npm install -g vercel
      - name: "Alias deployment"
        run: |
          if [ "${{ github.event.client_payload.git.ref }}" = "master" ]; then
            ALIAS="${{ github.event.repository.name }}-master"
          else
            ALIAS="${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}"
          fi
          vercel alias ${{ github.event.client_payload.url }} $ALIAS --token=${{ secrets.VERCEL_TOKEN }}
